- name: Check if dir exists
  shell: "{{ JENKINS_CLI_PREFIX }} get-job {{ item.name }}"
  ignore_errors: true
  register: check_dir

- name: Upload the template
  template:
    src: folder-job.xml
    dest: /tmp/folder-job.xml

- name: Create the job
  when: check_dir.rc == 3
  shell: "cat /tmp/folder-job.xml | {{ JENKINS_CLI_PREFIX }} create-job {{ item.name }}"

- name: Update the job
  when: check_dir.rc == 0
  shell: "cat /tmp/mb-job.xml | {{ JENKINS_CLI_PREFIX }} update-job {{ item.name }}"
