- name: Check Jenkins Connection
  shell: "{{ JENKINS_CLI_PREFIX }} who-am-i"

- name: Create Jenkins folder Job
  ansible.builtin.include_tasks:
    file: folders-job.yml
  loop:
    - {name: "CI-Pipelines", description: "ALL CI Pipelines"}

- name: Create Jenkins Multi Branch Pipelines Job
  ansible.builtin.include_tasks:
    file: mb-job.yml
  loop:
    - {name: "cart", repoName: "cart", dirName: "CI-Pipelines/"}
    - {name: "catalogue", repoName: "catalogue", dirName: "CI-Pipelines/"}
    - {name: "user", repoName: "user", dirName: "CI-Pipelines/"}
