- name: Check Jenkins Connection
  shell: "{{ JENKINS_CLI_PREFIX }} who-am-i"

- name: Create Jenkins Job
  loop:
    - {name: "sample1", repoName: "sample1"}
  block:
    - name: Check if job exists
      shell: "{{ JENKINS_CLI_PREFIX }} get-job {{ item.name }}"
      ignore_errors: true
      register: check_job

    - name: Generate unique job id
      shell: date|md5sum|awk '{print $1}'
      register: uniq_string

    - name: Upload the template
      template:
        src: job.xml
        dest: /tmp/job.xml

    - name: Create the job
      shell: "{{ JENKINS_CLI_PREFIX }} create-job {{ item.name }}"
      when: check_job.rc == 3

    - name: Update the job
      shell: "{{ JENKINS_CLI_PREFIX }} update-job {{ item.name }}"
      when: check_job.rc == 0
