- name: Check if {{ item.name }} job exists
  shell: "{{ JENKINS_CLI_PREFIX }} get-job {{item.dirName}}{{ item.name }}"
  ignore_errors: true
  register: check_job

- name: Generate unique job id
  shell: date|md5sum|awk '{print $1}'
  register: uniq_string

- name: Upload the template
  template:
    src: mb-job.xml
    dest: /tmp/mb-job.xml

- name: Create {{ item.name }} job
  when: check_job.rc == 3
  shell: "cat /tmp/mb-job.xml | {{ JENKINS_CLI_PREFIX }} create-job {{item.dirName}}{{ item.name }}"

- name: Update {{ item.name }} job
  when: check_job.rc == 0
  shell: "cat /tmp/mb-job.xml | {{ JENKINS_CLI_PREFIX }} update-job {{item.dirName}}{{ item.name }}"
