- name: Check if job exists
  shell: "{{ JENKINS_CLI_PREFIX }} get-job {{ item.name }}"
  ignore_errors: true
  register: check_job

- name: Generate unique job id
  shell: date|md5sum|awk '{print $1}'
  register: uniq_string

- name: Upload the template
  template:
    src: mb-job.xml
    dest: /tmp/mb-job.xml

- name: Create the job
  shell: "cat /tmp/mb-job.xml | {{ JENKINS_CLI_PREFIX }} create-job {{item.dirName}}{{ item.name }}"
  when: check_job.rc == 3

- name: Update the job
  shell: "cat /tmp/mb-job.xml | {{ JENKINS_CLI_PREFIX }} update-job {{item.dirName}}{{ item.name }}"
  when: check_job.rc == 0